### ISSUE TITLE
Get rid of composer-merge-plugin

### ISSUE THREAD

**Issue by balintbrews** [BluesparkLabs/spark#3]
* Remove `composer-merge-plugin`;
* Add instructions on how to include Spark in a project with this change: `autoload`, `scripts`;
* Make `composer/composer.drupal8.json` the main `composer.json` file of the project;
* Only install packages that Spark needs.

**Comment by jameswilson** [comment]
Marked this as a blocker because we need a solution before opening up spark for wider use across bluespark.

**Comment by jameswilson** [comment]
This issue will also dictate how we update the spark-example project, and could influence outcome on https://github.com/BluesparkLabs/spark-example/issues/2
